#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

/* Options for Waveform Generation Mode:
 * 1. TIMER0_NORMAL_MODE
 * 2. TIMER0_PWM_PHASE_CORRECT_MODE
 * 3. TIMER0_CTC_MODE
 * 4. TIMER0_FAST_PWM_MODE
 */
#define TIMER0_WAVEFORM_GENERATION_MODE   TIMER0_FAST_PWM_MODE

/* Options for OC0 Mode in Fast PWM:
 * 1. TIMER0_OC0_DISCONNECTED
 * 2. TIMER0_OC0_NON_INVERTING  (or TIMER0_OC0_CLEAR)
 * 3. TIMER0_OC0_INVERTING      (or TIMER0_OC0_SET)
 */
#define TIMER0_OC0_MODE                   TIMER0_OC0_NON_INVERTING

/* Options for Prescaler:
 * 1. TIMER0_NO_CLOCK
 * 2. TIMER0_PRESCALER_1
 * 3. TIMER0_PRESCALER_8
 * 4. TIMER0_PRESCALER_64
 * 5. TIMER0_PRESCALER_256
 * 6. TIMER0_PRESCALER_1024
 */
#define TIMER0_PRESCALER                  TIMER0_PRESCALER_64

#endif