#ifndef TMER0_CONFIG_H_
#define TMER0_CONFIG_H_
#define TIMER0_WAVEFORM_GENERATION_MODE   TIMER0_FAST_PWM_MODE
#define TIMER0_OC0_MODE                   TIMER0_OC0_NON_INVERTING
#define TIMER0_PRESCALER                  TIMER0_PRESCALER_64
#endif
